### PR TITLE
ci: Enable conformance test running from a PR

### PR DESCRIPTION
**Pull request by engedaam**
Fixes #N/A 

**Description**
- This PR allows users to run /karpenter conformance which will trigger scale testing runs from a PR build.

**How was this change tested?**
- `/karpenter conformance`

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by engedaam — COMMENTED** [review]
/karpenter conformance

**Review by engedaam — COMMENTED** [review]
/karpenter conformance

**Review by engedaam — COMMENTED** [review]
/karpenter conformance

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀

**Pull request merged**
