### PR TITLE
Adding custom multiplier and injected through config

### PR DESCRIPTION
**Pull request by rwilliams-r7**
Fixes # 

**Description**
Added code to allow a custom multiplier onto ondemand and spot pricing. This allows you to add a multiplier to prices that will be taken into consideration on which instance to use. This take's the same approach as autospotting (https://github.com/LeanerCloud/AutoSpotting/blob/master/START.md#configuration-of-autospotting). Prices can come from the Payer account of enterprise customers this leads to a problem as we cannot get the price data.
**How was this change tested?**

*

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [ ] No

**Release Note**

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by njtran** [comment]
Hey @rwilliams-r7, thanks for taking the time to make cut this PR. When considering new feature requests, we usually request that contributors create a design doc to validate why this change is needed, and what are the considerations you've taken to design the feature. This is especially needed when making any API changes, which looks like this PR has. 

If you've discussed this with a Karpenter maintainer, can you tag them in this as well? Otherwise, feel free to message us in the [kubernetes/karpenter-dev channel](https://kubernetes.slack.com/archives/C04JW2J5J5P). 

If you're up for designing, please check out some guidelines we have on the website: https://karpenter.sh/v0.27.3/contributing/design-guide/

**Comment by sftim** [comment]
> Prayer account

did you mean “Payer account”?

**Comment by jonathan-innis** [comment]
@rwilliams-r7 Marking this as stale until this is updated or a design doc is added. We'll close this in a few weeks if there's no objection or progress here.

**Comment by snorlaX-sleeps** [comment]
@jonathan-innis @ellistarn I work with @rwilliams-r7 am I ok to create a design document for this?
Do I need to create a new PR since this is closed?

**Comment by jonathan-innis** [comment]
@snorlaX-sleeps Yes! Feel free to create a design doc with the proposal and use-cases. It's probably preferable at this point to open a new PR with the design doc when you have it.

**Pull request closed without merging**
