### PR TITLE
chore: prepare v0.27.8 release

### PR DESCRIPTION
**Pull request by jmdeal**
Fixes #N/A 

**Description**
Bumps dependencies to fix vulnerabilities.

**How was this change tested?**
`make e2etests` in personal cluster, `make presubmit` and `govulncheck` against binary

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jmdeal — COMMENTED** [review]
/karpenter snapshot

**Review by jmdeal — COMMENTED** [review]
/karpenter snapshot

**Review by jmdeal — COMMENTED** [review]
/karpenter snapshot

**Review by jmdeal — COMMENTED** [review]
/karpenter snapshot

**Review by jmdeal — COMMENTED** [review]
/karpenter snapshot

**Review by jmdeal — COMMENTED** [review]
/karpenter snapshot

**Review by jmdeal — COMMENTED** [review]
/karpenter snapshot

**Review by jmdeal — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Pull request merged**
