### PR TITLE
update preview docs based on live docs

### PR DESCRIPTION
**Pull request by geoffcline**
**1. Issue, if available:**
changes made to /docs/ but not /pre-docs/

**2. Description of changes:**
copy changes from /docs/ into /pre-docs/

**3. Does this change impact docs?**
- [ x ] Yes, PR includes docs updates
- [ ] Yes, issue opened: *link to issue*
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by chrisnegus — APPROVED** [review]
This is ready to merge.
/lgtm

**Review by chrisnegus — APPROVED** [review]
/lgtm

**Review by ellistarn — APPROVED** [review]

**Pull request merged**
