### PR TITLE
Updated CODEOWNERS

### PR DESCRIPTION
**Pull request by njtran**
**1. Issue, if available:**

**2. Description of changes:**

**3. How was this change tested?**

**4. Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: *link to issue*
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bwagner5** [comment]
do we need this file or should we be using https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners ? 

with `CODEOWNERS` we can use our github team

**Comment by ellistarn** [comment]
Do we want the entire team to be able to merge? I'd rather be a bit more judicious on approvals.

**Comment by bwagner5** [comment]
IMO if they are in the aws-karpenter team, then they should have approval permissions. Why else would they need to be on that team?

**Comment by njtran** [comment]
The aws-karpenter team is pretty representative of who we want to be able to merge right now :) @ellistarn

**Review by bwagner5 — APPROVED** [review]
lgtm

**Pull request merged**
