### PR TITLE
chore: Improve Issue Templates

### PR DESCRIPTION
**Pull request by jonathan-innis**
Fixes # 

**Description**

We are currently using the old issue template markdown experience. This experience can be greatly improved by migrating to the new [YAML-based issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#about-yaml-syntax-for-issue-forms) that Github has introduced.

**How was this change tested?**

* 

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [x] No

**Release Note**

```release-note
None
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by tzneal** [comment]
Any way to preview this somewhere?

**Comment by jonathan-innis** [comment]
> Any way to preview this somewhere?

You can view the file directly to see what the form will look like. Beyond that, there isn't really a way to model the whole UI flow of clicking `New Issue` and selecting the issue type, but that should stay consistent with before.

**Comment by tzneal** [comment]
> > Any way to preview this somewhere?
> 
> You can view the file directly to see what the form will look like. Beyond that, there isn't really a way to model the whole UI flow of clicking `New Issue` and selecting the issue type, but that should stay consistent with before.

Ah, found it, thanks!

**Review by tzneal — APPROVED** [review]
lgtm

**Pull request merged**
