### PR TITLE
BREAKING CHANGE: Drop Alpha Settings and Add Beta Defaults to Chart

### PR DESCRIPTION
**Pull request by jonathan-innis**
Fixes #N/A 

**Description**

This PR performs the following actions which are now supported by the beta version of Karpenter:
1. Disable webhooks by default. If you were previously running Karpenter leveraging the webhooks on a version of K8s less than 1.25, you will now need to set `--set webhook.enabled=true` in the helm chart
2. Moves the logging default to be `info` now. If you are interested in more verbose error logging, you will now need to set the `--set logLevel=debug` value in the helm chart.
3. Updates the role permissions for the Karpenter role to reduce its permission scope since it's no longer using the webhook

This change also drops the `settings.Settings` struct now that this field is no longer supported in `kubernetes-sigs/karpenter`

**How was this change tested?**

`make presubmit`
`/karpenter snapshot`

**Does this change impact docs?**
- [x] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jmdeal — DISMISSED** [review]
LGTM 🚀

**Review by jmdeal — APPROVED** [review]
LGTM 🚀

**Review by engedaam — DISMISSED** [review]
LGTM 🚀

**Review by jmdeal — APPROVED** [review]
LGTM 🚀

**Pull request merged**
