### PR TITLE
docs: correct spelling of EventBridge.

### PR DESCRIPTION
**Pull request by rpdedeus**
EvnetBridge to EventBridge.

Fixes # 

**Description**

**How was this change tested?**

*

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [x] No

**Release Note**

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by tzneal — APPROVED** [review]
lgtm, thanks!

**Review by tzneal — CHANGES_REQUESTED** [review]
Actually, I missed something. This needs to be updated in the /preview/ docs as well, each new release is generated from /preview/.

**Comment by rpdedeus** [comment]
> This needs to be updated in the /preview/ docs as well, each new release is generated from /preview/.

Looks to me like it has already been addressed here:
https://github.com/aws/karpenter/pull/3189/files

**Review by tzneal — APPROVED** [review]
lgtm

**Pull request merged**
