### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by bwagner5**
**1. Issue, if available:**
https://github.com/aws/karpenter/issues/1131

**2. Description of changes:**
 - This is mostly [khoa-hatch](https://github.com/khoa-hatch)'s PR https://github.com/aws/karpenter/pull/1477 
   - I've rebased and fixed conflicts
 - Fixed a few odds and ends in the userdata script for windows.

**3. How was this change tested?**
 - Manually tested a windows node joining the cluster with a windows pod

**4. Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: *link to issue*
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by MrBones757** [comment]
Do you need any help testing this?
[jitterjuice](https://github.com/jitterjuice) and i would be happy to deploy an rc / pre-release of this in our env and test against our infra - we're approaching a time when we were going to start looking at this functionality ourselves, behind schedule where we thought we would be, but at this point newish.

**Comment by bwagner5** [comment]
> Do you need any help testing this? [jitterjuice](https://github.com/jitterjuice) and i would be happy to deploy an rc / pre-release of this in our env and test against our infra - we're approaching a time when we were going to start looking at this functionality ourselves, behind schedule where we thought we would be, but at this point newish.

More testing would be great! I've done some rudimentary testing so far and I've at least got nodes something up, going to Ready, and deploying the windows pause pods to it. Let me see how to get a snapshot build out of this PR. @spring1843 can you help with this?

**Comment by bwagner5** [comment]
@MrBones757 here are the snapshot builds for this PR:

public.ecr.aws/karpenter-snapshots/controller:6cf6144bbe6265e2ed902168fb2790421f2d6c0d

public.ecr.aws/karpenter-snapshots/webhook:6cf6144bbe6265e2ed902168fb2790421f2d6c0d

**Comment by MrBones757** [comment]
Thanks! Will get onto this in a few hours!!

**Comment by MrBones757** [comment]
Not sure how easy this would be to integrate, but for windows support, allowing "node.kubernetes.io/windows-build" in the requirements section of the provisioner:
https://kubernetes.io/docs/reference/labels-annotations-taints/#nodekubernetesiowindows-build

from the docs:
"When the kubelet is running on Microsoft Windows, it automatically labels its node to record the version of Windows Server in use."

allowing karp to use this info would be handy, i.e, request a windows node of a particular version as windows containers are OS version dependent..
i guess the user would have to configure this in the provisioner, and the workload would need to consume the appriate selector, but if you're using windows on k8s i would assume the user would already know about this limitation / requirement, though a note could be added to the docs about multi version support if thats a desired element

**Comment by bwagner5** [comment]
> Not sure how easy this would be to integrate, but for windows support, allowing "node.kubernetes.io/windows-build" in the requirements section of the provisioner: https://kubernetes.io/docs/reference/labels-annotations-taints/#nodekubernetesiowindows-build
> 
> from the docs: "When the kubelet is running on Microsoft Windows, it automatically labels its node to record the version of Windows Server in use."
> 
> allowing karp to use this info would be handy, i.e, request a windows node of a particular version as windows containers are OS version dependent.. i guess the user would have to configure this in the provisioner, and the workload would need to consume the appriate selector, but if you're using windows on k8s i would assume the user would already know about this limitation / requirement, though a note could be added to the docs about multi version support if thats a desired element
> 
> Ive got the versions you linked above running in our environment now, and will work on running some tests over the next day or few.

Awesome! Thanks for testing this out! 

We were discussing the versioning problem this morning. We need to support AMI Family versions in the AWS Cloud Provider anyways, so it may make sense to roll this into the cloud provider spec as a version field for the AMI Family. I suspect that users will want to run an isolated provisioner for windows nodes and likely for a specific Windows version. We could probably label the nodes with the `node.kubernetes.io/windows-build` that is tied to the AMI Family version.

**Comment by MrBones757** [comment]
> I suspect that users will want to run an isolated provisioner for windows nodes and likely for a specific Windows version. We could probably label the nodes with the `node.kubernetes.io/windows-build` that is tied to the AMI Family version.

This is exactly what I have in my environment right now
When you stand up a windows node, it automatically adds this annotation in the kubelet
I have a provisioner set up for 20H2 and will have one for LTSC2022 when that is supported.

see the following links for build no info:
(https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info)
(https://kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-containers/)

The idea here was to support, in the provisioner, the node.kubernetes.io/windows-build label like:

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: windows-20h2-provisioner
spec:
  requirements:
    - key: "node.kubernetes.io/windows-build"
      operator: Equals
      values: 10.0.19042
```
and
```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: windows-2019-ltsc-provisioner
spec:
  requirements:
    - key: "node.kubernetes.io/windows-build"
      operator: Equals
      values: 10.0.17763
```

where for this label, the operator must be "Equal", not "In" untill msft supports running more than one container os on the host OS.

Workloads would then have to allow one or more of these depending on the container the workload is running.
For example, if the workload's container supported both 2019 and 20h2 it could allow this in its node selector rules, and karp would choose one (maybe newest by version?) and allocate the workload there

and if the workload's image supports only one, the user would annotate that version only

**Comment by MrBones757** [comment]
I've been working on the integration of this into out environment along with gitlab-runner (as thats the current usecase for karpenter - build environment compute)

I have confirmed the linux side is still working as expected still, and i have indeed been able to get a windows node to spin up.
this is testing a lot of components in my environment as this is the first actual proper test of Windows so far, so needing to work though issues with csi drivers etc also, looking good so far though..

would be good if we could get the windows startup time to < 5 mins, but that's definitely out of scope haha
i will work on some fine tuning of my test environment tomorrow and do some larger scale testing and update this thread again.

**Comment by MrBones757** [comment]
I've done some further testing on this,
background: due to the way gitlab-runner works on k8s, I require the ability to be able to set node.kubernetes.io/windows-build in its node selectors so it can appropriately choose the right helper images for build context.

node provisioning in general looks good to me, i was able to get windows node to spin up and run, with pods assigned, but to be of any actual use in our environment, I need to be able to specify that windows-build label

once I'm able to consume that field I think I should be good to go, and would be able to use this windows support.

**Comment by shirwahersi** [comment]
@MrBones757 / @bwagner5 - Any update on this PR?

**Comment by bwagner5** [comment]
> @MrBones757 / @bwagner5 - Any update on this PR?

Hey @shirwahersi, I don't have any updates yet.  I've been out for a bit and need to dig into this deeper wrt how the Windows versioning builds will work within Karpenter.  This will be a long haul PR, but it's a good WIP currently.

**Comment by barryib** [comment]
@bwagner5 I hope you're doing good. Is there something we can do to help move this ?

**Comment by bwagner5** [comment]
Hey @barryib  ! Windows support has been deprioritized based on some other larger features we are working on.  We're working on support for custom AMIs and removing the need for LTs. That work will come in handy supporting windows in a more generic way, so we'll likely wait on all of that to land in Karpenter first. The next step will be versioning which we've discussed in this PR a little. Supporting another AMI Family is quite a bit of work for a good experience, so another thing we need and are currently working on is a more comprehensive test infrastructure.  So unfortunately this PR is paused right now, but I'd hope to pick this back up later this year.

**Comment by barryib** [comment]
> Hey @barryib ! Windows support has been deprioritized based on some other larger features we are working on. We're working on support for custom AMIs and removing the need for LTs. That work will come in handy supporting windows in a more generic way, so we'll likely wait on all of that to land in Karpenter first. The next step will be versioning which we've discussed in this PR a little. Supporting another AMI Family is quite a bit of work for a good experience, so another thing we need and are currently working on is a more comprehensive test infrastructure. So unfortunately this PR is paused right now, but I'd hope to pick this back up later this year.

Thanks @bwagner5 for the update. It's clear, we're going to try the cluster autocaler way in the meantime.

Thanks again for your work on this project.

**Comment by bwagner5** [comment]
Closing for now

**Comment by touseefspeaks** [comment]
Do we have anything going on supporting windows nodegroup ?

**Pull request closed without merging**
