### PR TITLE
ci: Enable control plane logging for e2e tests

### PR DESCRIPTION
**Pull request by jonathan-innis**
Fixes #N/A 

**Description**

This PR updates the `create-cluster.yaml` action to create clusters with log retention enabled for 30d.

**How was this change tested?**

`/karepenter snapshot`

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by njtran — DISMISSED** [review]

**Review by njtran — APPROVED** [review]

**Pull request merged**
