### PR TITLE
Feat: Default to 2 replicas and a rolling deployment strategy

### PR DESCRIPTION
**Pull request by ellistarn**
Fixes # 

**Description**

- Run in HA mode by default
- Speeds up dev loop, since we don't need to wait for the pod to terminate after 30 seconds

**How was this change tested?**

*

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [X] No

**Release Note**

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by FernandoMiguel** [comment]
yay
I can finally remove
```hcl
      {
        name  = "replicas"
        value = "2"
        type  = "string"
      },
```
from our internal SET values code :D

**Review by suket22 — APPROVED** [review]

**Review by jonathan-innis — APPROVED** [review]
🚀

**Comment by bytestream** [comment]
@ellistarn sorry to jump on this thread, but how do I change this back to 1 if I'm using Fargate profiles? I've just followed https://karpenter.sh/preview/getting-started/getting-started-with-eksctl/ and I don't need HA (a replica of carpenter) for my usage.

**Comment by jonathan-innis** [comment]
You should be able to set the replicas in the helm chart by doing `--set replicas=1`

**Pull request merged**
