### PR TITLE
chore: k8s latest packages

### PR DESCRIPTION
**Pull request by sadath-12**
Fixes #N/A 

**Description**

updating k8s packages to latest version to support new features

**How was this change tested?**

```make presubmit```

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — DISMISSED** [review]
LGTM 🚀

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by njtran — APPROVED** [review]

**Pull request merged**
