### PR TITLE
Init Korean translation

### PR DESCRIPTION
**Pull request by whoo3474**
**1. Issue, if available:**

**2. Description of changes:**
- As the first Korean translation, index.html was translated.
- add website/content/ko folder and Translate the index.html into Korean.

**3. How was this change tested?**
n/a

**4. Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: *link to issue*
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by felix-zhe-huang** [comment]
Thank you very much! Feeling excited about having another language available for the webpage.
Curious, I don't see the content when I click preview.
https://deploy-preview-1124--karpenter-docs-prod.netlify.app/ko/

**Comment by ellistarn** [comment]
This is really cool. I'm a bit nervous about the maintainability of this in the long term. Our docs can and do evolve over time, so I'm a little bit wary of not being able to keep things accurate unless we have someone dedicated that can do this translation work. I'm not opposed to merging, but another option to consider is to write a blog in korean that translates karpenter's index. Blogs have a greater expectation of staleness while still being extremely useful for users. We would, of course, link to that from Karpenter's main page.

**Comment by whoo3474** [comment]
@ellistarn 

Thank you so much for your opinion.

So far, I haven't seen many cases used in Korea.
But I think karpenter is a good project, and I want more people to use and contribute, so I want to translate little by little as of now.
By doing so, I believe that many people will participate in Korean translation while maintaining accurate content.

Which would be better to merge or write down a new blog?
I wonder how blogs should be conducted.

**Comment by whoo3474** [comment]
@felix-zhe-huang 

I can't believe there was a function to see preview when building!
This is really cool!
There was a lack because it was awkward for me to contribute.
I'll check it again and upload it.
Thank you.

**Comment by whoo3474** [comment]
Does creating a blog mean creating a subdomain or purchasing and using a new domain?
I would appreciate it if you could give me an example or advice.
Enter "https://deploy-preview-1124--karpenter-docs-prod.netify.app/ko/" to make it work properly!
It was my first time playing Hugo, but it was fun.

**Comment by ellistarn** [comment]
> Does creating a blog mean creating a subdomain or purchasing and using a new domain? I would appreciate it if you could give me an example or advice. Enter "https://deploy-preview-1124--karpenter-docs-prod.netlify.app/ko/" to make it work properly! It was my first time playing Hugo, but it was fun.

I'd look at something like medium (e.g. https://evgenibir.medium.com/aws-karpenter-6246c6efc718).

**Pull request closed without merging**
