### PR TITLE
snapshot build test

### PR DESCRIPTION
**Pull request by tzneal**
Fixes # 

**Description**

**How was this change tested?**

*

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [ ] No

**Release Note**

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by tzneal — COMMENTED** [review]
/karpenter snapshot

**Review by bwagner5 — APPROVED** [review]
/karpenter snapshot

**Review by jonathan-innis — APPROVED** [review]
/karpenter snapshot

**Pull request closed without merging**
