### PR TITLE
test: Fix E2E test permissions, upgrade, consolidation, and integration tests

### PR DESCRIPTION
**Pull request by jonathan-innis**
Fixes #N/A 

**Description**

- This PR updates the IAM Cloudformation permissions used for the permission boundary for the GithubActions role.
- This PR also updates test that is run during the upgrade test to be `Beta/Integration`
- It updates the Monitor to handle watching nodes that are owned by NodePools so consolidation tests work
- It updates bugs in the Integration test cases
- It merges the Utilization test case/suite into the Integration test suite
- The cloudformation policy had to be condensed here to avoid going over the managed instance profile character limit

**How was this change tested?**

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by engedaam — APPROVED** [review]
LGTM 🚀

**Pull request merged**
