### PR TITLE
feat:add-extra-manifest-objects-to-helm-chart

### PR DESCRIPTION
**Pull request by evanshoshan**
…sources

**Description**

Added extra objects deployment to helm chart to support dynamic creation of K8s manifests via helm values files

**How was this change tested?**

- helm template validation 
- helm lint 

**Does this change impact docs?**
- [ x] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [ ] No

**Release Note**

```release-note
None
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jonathan-innis** [comment]
@evanshoshan Can you explain why this is needed? Why not just deploy your K8s objects through some other mechanism like helm chart dependencies rather than injecting these K8s manifests directly into the chart?

**Comment by nxf5025** [comment]
> @evanshoshan Can you explain why this is needed? Why not just deploy your K8s objects through some other mechanism like helm chart dependencies rather than injecting these K8s manifests directly into the chart?

@jonathan-innis - Not the PR author, but I can chime in here...This is starting to become a common trend with helm charts. A few other examples can be found here:

- [Grafana](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/extra-manifests.yaml)
- [Traefik](https://github.com/traefik/traefik-helm-chart/blob/master/traefik/templates/extra-objects.yaml)
- [ArgoCD](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/extra-manifests.yaml)

This is really just a convenience update so you don't need to worry about a subchart for an extra file or two. For more advanced cases I definitely agree setting up a dependency would be the best route, but I don't see any downside to adding this in.

**Comment by jonathan-innis** [comment]
@nxf5025 Thanks for the context here. You're right that this seems to be more and more of a pattern in the chart community. Sounds good to me.

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀

**Pull request merged**
