### PR TITLE
feat: filter out more expensive spot instance types

### PR DESCRIPTION
**Pull request by tzneal**
Fixes # 

**Description**

Only launch spot instance types that are cheaper than the cheapest on-demand instance type would have been.  This ensures that adding spot support to your provisioners won't increase your cluster cost.

**How was this change tested?**

*

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [ ] No

**Release Note**

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by bwagner5 — APPROVED** [review]
LGTM

**Review by bwagner5 — APPROVED** [review]
LGTM

**Review by ellistarn — COMMENTED** [review]
Nice work! Curious if this could live in karpenter-core, since other providers may want to benefit from this functionality.

**Comment by ellistarn** [comment]
> We give a lot of meaning to the "capacity-type" label.

Yeah -- I've love for karpenter-core to be totally capacity-type agnostic, but not sure if it's possible today. It's currently encoded in the cloudprovider offerings API. Happy either way.

**Review by ellistarn — APPROVED** [review]

**Pull request merged**
