### PR TITLE
Fixed link for provisioner API

### PR DESCRIPTION
**Pull request by yutachaos**
**1. Issue, if available:**
- https://github.com/aws/karpenter/issues/1159

**2. Description of changes:**
- fixed broken link.

**3. How was this change tested?**

**4. Does this change impact docs?**
- [x] Yes, PR includes docs updates
- [x] Yes, issue opened: *link to issue*
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ellistarn** [comment]
FYI: https://github.com/aws/karpenter/pull/1161

**Comment by ellistarn** [comment]
Though yours looks more comprehensive.

**Comment by chrisnegus** [comment]
Locations of some of the files changed, so I used this information to create [PR 1172](https://github.com/aws/karpenter/pull/1172) I believe we can close this now.

**Comment by yutachaos** [comment]
@chrisnegus 
I see. Thanks

**Pull request closed without merging**
