### PR TITLE
ci: publish image with tag=short commit in CI

### PR DESCRIPTION
**Pull request by tuananh**
Signed-off-by: Tuan Anh Tran <me@tuananh.org>

**1. Issue, if available:**

https://github.com/aws/karpenter/issues/708

**2. Description of changes:**

Add a step in `Makefile` named: `publish-ci-image` and add it to `make ci` step
Build and publish the image using git short commit for tag

**3. Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [x] Yes, issue opened: https://github.com/aws/karpenter/issues/708
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ellistarn** [comment]
Hey @tuananh, thanks for the PR. However, Github Actions doesn't currently have permission to push to the release repository. Our releases are currently unfortunately manual at the moment. I also don't want to block CI on image build, since the current runtime is at the edge of my comfort (~10m). 

I'd love to explore some sort of prow/tekton solution that the karpenter team maintains. If you're interested in taking up this effort, let's talk next steps!

**Comment by tuananh** [comment]
> 

yeah i'm interested. where will the tekton instance be running on btw?

so if im understanding it right, we will just setup a event listener on tekton and it will pick it up from there?

**Comment by ellistarn** [comment]
> > 
> 
> yeah i'm interested. where will the tekton instance be running on btw?
> 
> so if im understanding it right, we will just setup a event listener on tekton and it will pick it up from there?

You can assume there will be some cluster running somewhere (eks?). I haven't looked into the deeply, but it would be nice to poll github somehow and trigger pipeline executions (i.e. image build, test suite, etc). Are you able to attend our [working group](https://github.com/aws/karpenter/blob/main/WORKING_GROUP.md) to discuss further?

**Comment by tuananh** [comment]
> > yeah i'm interested. where will the tekton instance be running on btw?
> > so if im understanding it right, we will just setup a event listener on tekton and it will pick it up from there?
> 
> You can assume there will be some cluster running somewhere (eks?). I haven't looked into the deeply, but it would be nice to poll github somehow and trigger pipeline executions (i.e. image build, test suite, etc). Are you able to attend our [working group](https://github.com/aws/karpenter/blob/main/WORKING_GROUP.md) to discuss further?

added to the calendar :)

**Pull request closed without merging**
