### PR TITLE
added missing code block closer

### PR DESCRIPTION
**Pull request by idokrn**
**1. Issue, if available:**

**2. Description of changes:**
Fixing a typo. missing code block closer

**3. How was this change tested?**
previewed on MD editor 

**4. Does this change impact docs?**
- [x] Yes, PR includes docs updates

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ellistarn — COMMENTED** [review]
Nice catch! It looks like this bug dates all the way back until v0.5.3. Do you mind updating this in all places as well as `preview`?

**Comment by idokrn** [comment]
> Nice catch! It looks like this bug dates all the way back until v0.5.3. Do you mind updating this in all places as well as `preview`?
@ellistarn
done, sorry for the forced push had a little fight with git and that was the only way to win

**Comment by bwagner5** [comment]
> > Nice catch! It looks like this bug dates all the way back until v0.5.3. Do you mind updating this in all places as well as `preview`?
> 
> @ellistarn done, sorry for the forced push had a little fight with git and that was the only way to win

Nice! All that matters is that you won! 🚀

**Review by bwagner5 — APPROVED** [review]
lgtm! thanks!!!!

**Pull request merged**
