### PR TITLE
docs: wrong value - missing settings.

### PR DESCRIPTION
**Pull request by nirroz93**
Fixes # 

**Description**

**How was this change tested?**

*

**Does this change impact docs?**
- [X] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [ ] No

**Release Note**

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by bwagner5 — CHANGES_REQUESTED** [review]
can you copy these over to the `content/en/preview` docs as well?

**Comment by nirroz93** [comment]
@bwagner5 done

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀

**Review by ellistarn — APPROVED** [review]
Nice catch!

**Review by bwagner5 — APPROVED** [review]
LGTM

**Pull request merged**
