### PR TITLE
chore: bump aws-sdk-go to aws-sdk-go-v2

### LINKED ISSUE #3411: Bump `github.com/aws/aws-sdk-go` to `github.com/aws/aws-sdk-go-v2`
### Tell us about your request

AWS is now supporting the latest version of the AWS Go SDK which is `github.com/aws/aws-sdk-go-v2`. We should upgrade all mentions of the package `github.com/aws/aws-sdk-go` to the newest version to stay up-to-date and to avoid getting deprecated on the older version.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

N/A

### Are you currently working around this issue?

N/A

### Additional Context

_No response_

### Attachments

_No response_

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by khareyash05**
Fixes #3411  

**Description**

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [X] No

**Release Note**

```release-note
NONE
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by njtran** [comment]
Looks like CI tests are failing. I see you've updated go.mod, but no go.sum or test/go.mod or test/go.sum changes. Can you run `make presubmit` and to see if that works locally and add in the changes?

**Comment by khareyash05** [comment]
> Contributor

I am getting this error `module github.com/aws/aws-sdk-go-v2@latest found (v1.18.0), but does not contain package github.com/aws/aws-sdk-go-v2/aws/session` on running `make presubmit`. I checked upon the repo and could not find `aws/session` in v2 repo. Do I have to keep the original `aws-sdk-go` as well alongwith `aws-sdk-go-v2`?

**Comment by khareyash05** [comment]
> Looks like CI tests are failing. I see you've updated go.mod, but no go.sum or test/go.mod or test/go.sum changes. Can you run `make presubmit` and to see if that works locally and add in the changes?

I got this error 
image
on running `make presubmit`.Kindly help

**Comment by jonathan-innis** [comment]
@khareyash05 Have you tried running `make toolchain` locally? I'm not sure if you have seen this but here's our [Developer Loops Docs](https://karpenter.sh/docs/contributing/development-guide/#developer-loop) for setting up your environment

**Comment by engedaam** [comment]
@khareyash05 any updates?

**Pull request closed without merging**
