### PR TITLE
chore: Remove `aws.nodeNameConvention` from Karpenter settings

### LINKED ISSUE #3748: Karpenter created nodes NotReady with Resource based naming
### Version

__Karpenter Version:__ v0.27.2

__Kubernetes Version:__ EKS v1.26

### Expected Behavior

https://github.com/aws/karpenter/pull/3146 was designed to make [resource based naming](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-naming.html#instance-naming-choose) work with Karpenter

When setting a subnet to resource based naming, and setting Karpenter nodeNameConvention to `resource-name` configuration as below:
```
settings:
  # -- AWS-specific configuration values
  aws:
    # -- The node naming convention (either "ip-name" or "resource-name")
    nodeNameConvention: "resource-name"

```
Nodes should successfully join the cluster with a node name that is the EC2 instance id.

### Actual Behavior

Node stays as NotReady

```
i-0558290eed951076c                                  NotReady   <none>   12h                          beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,k8s.io/cloud-provider-aws=0205f4a6b368c655d14528c162719ff1,karpenter.k8s.aws/instance-ami-id=ami-07d5b917f72cb13ac,karpenter.k8s.aws/instance-category=r,karpenter.k8s.aws/instance-cpu=2,karpenter.k8s.aws/instance-encryption-in-transit-supported=true,karpenter.k8s.aws/instance-family=r6a,karpenter.k8s.aws/instance-generation=6,karpenter.k8s.aws/instance-hypervisor=nitro,karpenter.k8s.aws/instance-memory=16384,karpenter.k8s.aws/instance-network-bandwidth=781,karpenter.k8s.aws/instance-pods=100,karpenter.k8s.aws/instance-size=large,karpenter.sh/capacity-type=spot,karpenter.sh/provisioner-name=bottlerocket,kubernetes.io/arch=amd64,kubernetes.io/os=linux,node.kubernetes.io/instance-type=r6a.large,os-distribution=bottlerocket,topology.kubernetes.io/region=us-west-2,topology.kubernetes.io/zone=us-west-2b
```

### Steps to Reproduce the Problem

Create a VPC and subnet configured to use EC2 resource based naming.

Set Karpenter nodeNameConvention to `resource-name` configuration as below (helm chart config):
```
settings:
  # -- AWS-specific configuration values
  aws:
    # -- The node naming convention (either "ip-name" or "resource-name")
    nodeNameConvention: "resource-name"
```

Have Karpenter launch an EC2 instance. 

### Resource Specs and Logs

Nothing obvious in Karpenter logs. I do see the following

```
k describe node i-0558290eed951076c

Lease:              Failed to get lease: leases.coordination.k8s.io "i-0558290eed951076c" not found
Conditions:
  Type             Status    LastHeartbeatTime                 LastTransitionTime                Reason                   Message
  ----             ------    -----------------                 ------------------                ------                   -------
  Ready            Unknown   Tue, 11 Apr 2023 21:31:56 -0700   Tue, 11 Apr 2023 21:33:00 -0700   NodeStatusNeverUpdated   Kubelet never posted node status.
  MemoryPressure   Unknown   Tue, 11 Apr 2023 21:31:56 -0700   Tue, 11 Apr 2023 21:33:00 -0700   NodeStatusNeverUpdated   Kubelet never posted node status.
  DiskPressure     Unknown   Tue, 11 Apr 2023 21:31:56 -0700   Tue, 11 Apr 2023 21:33:00 -0700   NodeStatusNeverUpdated   Kubelet never posted node status.
  PIDPressure      Unknown   Tue, 11 Apr 2023 21:31:56 -0700   Tue, 11 Apr 2023 21:33:00 -0700   NodeStatusNeverUpdated   Kubelet never posted node status.

Events:
  Type     Reason               Age                   From       Message
  ----     ------               ----                  ----       -------
  Warning  FailedInflightCheck  37m (x21 over 11h)    karpenter  Expected resource "memory" didn't register on the node
  Warning  FailedInflightCheck  17m (x10 over 10h)    karpenter  Expected resource "ephemeral-storage" didn't register on the node
  Warning  FailedInflightCheck  7m35s (x33 over 11h)  karpenter  Expected resource "cpu" didn't register on the node
```

This is a Bottlerocket node. Checking kubelet logs shows the following
```
Apr 12 17:38:41 ip-10-0-248-163.us-west-2.compute.internal kubelet[1233]: I0412 17:38:41.559235    1233 kubelet_node_status.go:70] "Attempting to register node" node="ip-10-0-248-163.us-west-2.compute.internal"
Apr 12 17:38:41 ip-10-0-248-163.us-west-2.compute.internal kubelet[1233]: E0412 17:38:41.561272    1233 kubelet_node_status.go:92] "Unable to register node with APIserver" err="nodes \"ip-10-0-248-163.us-west-2.compute.internal\" is forbidden: node \"i-0558290eed951076c.us-west-2.compute.internal\" is not allowed to modify node \"ip-10-0-248-163.us-west-2.compute.internal\"" node="ip-10-0-248-163.us-west-2.compute.internal"
Apr 12 17:38:46 ip-10-0-248-163.us-west-2.compute.internal kubelet[1233]: E0412 17:38:46.719869    1233 eviction_manager.go:261] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"ip-10-0-248-163.us-west-2.compute.internal\" not found"
Apr 12 17:38:46 ip-10-0-248-163.us-west-2.compute.internal kubelet[1233]: E0412 17:38:46.728388    1233 controller.go:146] failed to ensure lease exists, will retryin 7s, error: leases.coordination.k8s.io "ip-10-0-248-163.us-west-2.compute.internal" is forbidden: User "system:node:i-0558290eed951076c.us-west-2.compute.internal" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease": can only access node lease with the same name as the requestingnode
Apr 12 17:38:48 ip-10-0-248-163.us-west-2.compute.internal kubelet[1233]: I0412 17:38:48.562705    1233 kubelet_node_status.go:70] "Attempting to register node" node="ip-10-0-248-163.us-west-2.compute.internal"
Apr 12 17:38:48 ip-10-0-248-163.us-west-2.compute.internal kubelet[1233]: E0412 17:38:48.564650    1233 kubelet_node_status.go:92] "Unable to register node with APIserver" err="nodes \"ip-10-0-248-163.us-west-2.compute.internal\" is forbidden: node \"i-0558290eed951076c.us-west-2.compute.internal\" is not allowed to modify node \"ip-10-0-248-163.us-west-2.compute.internal\"" node="ip-10-0-248-163.us-west-2.compute.internal"
Apr 12 17:38:53 ip-10-0-248-163.us-west-2.compute.internal kubelet[1233]: E0412 17:38:53.730620    1233 controller.go:146] failed to ensure lease exists, will retryin 7s, error: leases.coordination.k8s.io "ip-10-0-248-163.us-west-2.compute.internal" is forbidden: User "system:node:i-0558290eed951076c.us-west-2.compute.internal" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease": can only access node lease with the same name as the requestingnode
Apr 12 17:38:54 ip-10-0-248-163.us-west-2.compute.internal kubelet[1233]: I0412 17:38:54.659346    1233 log.go:198] http: TLS handshake error from 10.0.187.181:43078: no serving certificate available for the kubelet
Apr 12 17:38:55 ip-10-0-248-163.us-west-2.compute.internal kubelet[1233]: I0412 17:38:55.565931    1233 kubelet_node_status.go:70] "Attempting to register node" node="ip-10-0-248-163.us-west-2.compute.internal"
Apr 12 17:38:55 ip-10-0-248-163.us-west-2.compute.internal kubelet[1233]: E0412 17:38:55.568041    1233 kubelet_node_status.go:92] "Unable to register node with APIserver" err="nodes \"ip-10-0-248-163.us-west-2.compute.internal\" is forbidden: node \"i-0558290eed951076c.us-west-2.compute.internal\" is not allowed to modify node \"ip-10-0-248-163.us-west-2.compute.internal\"" node="ip-10-0-248-163.us-west-2.compute.internal"
Apr 12 17:38:56 ip-10-0-248-163.us-west-2.compute.internal kubelet[1233]: I0412 17:38:56.442672    1233 log.go:198] http: TLS handshake error from 10.0.144.183:55088: no serving certificate available for the kubelet
Apr 12 17:38:56 ip-10-0-248-163.us-west-2.compute.internal kubelet[1233]: E0412 17:38:56.720884    1233 eviction_manager.go:261] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"ip-10-0-248-163.us-west-2.compute.internal\" not found"
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by jonathan-innis**
Fixes #3748 

**Description**

Remove `aws.nodeNameConvention` from `karpenter-global-settings`. This can be removed since there is no reliance on the node name anymore due to #3408.

**How was this change tested?**

* `make presubmit`
* Manually deployed `karpenter-global-settings` with `aws.nodeNameConvention` and saw no errors

**Does this change impact docs?**
- [x] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [ ] No

**Release Note**

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ellistarn** [comment]
We need a breaking upgrade note, right?

**Comment by jonathan-innis** [comment]
> We need a breaking upgrade note, right?

We could potentially mention this in the docs but there should be no breaking behavior for users that currently specify it. It just becomes an ignored setting

**Comment by bwagner5** [comment]
> > We need a breaking upgrade note, right?
> 
> We could potentially mention this in the docs but there should be no breaking behavior for users that currently specify it. It just becomes an ignored setting

I think a note is warranted since kOps relies on this setting and it would be nice to call out why we have removed it and that it is safe for them to remove.

**Review by ellistarn — APPROVED** [review]
Awesome fix!

**Comment by mbevc1** [comment]
Was this included in v0.28.0? Seems like it's still taking the config value via Helm and breaking the provisioning, i.e. adding additional resource:
```
i-0404b04f68f267c87                                     Unknown   <none>   54s                           c5.xlarge       eu-west-1c   amd64   on-demand
ip-192-168-17-190.eu-west-1.compute.internal            Ready     <none>   33s     v1.27.1-eks-2f008fe   c5.xlarge       eu-west-1c   amd64   on-demand
```

**Pull request merged**
