### PR TITLE
Release PR snapshot upon approval message with `/release`

### PR DESCRIPTION
**Pull request by spring1843**
**1. Issue, if available:**

**2. Description of changes:**
To test snapshot releases

**3. How was this change tested?**

**4. Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: *link to issue*
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by bwagner5 — APPROVED** [review]
Badly needed change! Thanks!!!!!

Should we have tests for this particular change?

**Comment by spring1843** [comment]
hmmm

**Review by bwagner5 — DISMISSED** [review]
lgtm

**Review by bwagner5 — APPROVED** [review]
/snapshot

**Pull request merged**
