### PR TITLE
feat: support for ImageGCHighThresholdPercent and ImageGCLowThresholdPercent

### PR DESCRIPTION
**Pull request by lucass4**
Add a new feature to support https://github.com/aws/karpenter/issues/3110

#### Description
Add support for ImageGCHighThresholdPercent and ImageGCLowThresholdPercent.

#### How was this change tested?
Tested using unit tests and integration test

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ellistarn — DISMISSED** [review]
/karpenter snapshot

Fantastic!

**Review by ellistarn — APPROVED** [review]

**Comment by ellistarn** [comment]
I think this needs a rebase to start passing.

**Review by ellistarn — DISMISSED** [review]

**Comment by lucass4** [comment]
> I think this needs a rebase to start passing.

done! Added an extra test for the happy path too. Thanks!

**Review by ellistarn — APPROVED** [review]

**Comment by alex-berger** [comment]
Looks like this PR removed `TopologyManagerPolicy` field from the `BottlerocketKubernetes` struct [see diff](https://github.com/aws/karpenter/pull/3264/files#diff-a3cbfce28a0ecf65dea19fa09613d36dc9d5c653ff993472e70820de27f03efeL70). Was this by intention?

**Comment by hawkesn** [comment]
Thanks for this @lucass4 !

**Pull request merged**
