### PR TITLE
docs: Update CloudFormation to handle v1beta1 permissions

### PR DESCRIPTION
**Pull request by jonathan-innis**
Fixes #N/A 

**Description**

Updates the CloudFormation template shipped with the Getting Started guide to use v1beta1 permissions. This also ensures that we are deploying the Karpenter controller IAM permissions with an additional policy that gives the controller the alpha permissions so that we can ensure that scenarios that are testing alpha and beta simultaneously will work.

**How was this change tested?**

`make apply` with the new permissions

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by chrisnegus — COMMENTED** [review]
The cloudformation.yaml file looks good to me. I'll update my PR to match the new contents of that file: https://github.com/aws/karpenter/pull/4394

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by tzneal — APPROVED** [review]
lgtm

**Pull request merged**
