### PR TITLE
test: Move metric relabeling to service monitor layer

### PR DESCRIPTION
**Pull request by jonathan-innis**
Fixes #N/A 

**Description**

- Move metric relabelings that add additional info to the metrics into the `ServiceMonitor`
- Reduces metric duplication between both performing a separate scrape job and using the servicemonitor for service discovery

**How was this change tested?**

`make apply` on local cluster

**Does this change impact docs?**
- [] Yes, PR includes docs updates
- [] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by njtran — APPROVED** [review]

**Pull request merged**
