### PR TITLE
move Grafana under "next steps" heading

### PR DESCRIPTION
**Pull request by geoffcline**
**1. Issue, if available:**

**2. Description of changes:**
I'm not sure where we landed on if Grafana docs should currently be public.

Regardless, they should be at the end of the getting started guide. 

**3. Does this change impact docs?**
- [X] Yes, PR includes docs updates
- [ ] Yes, issue opened: *link to issue*
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ellistarn — COMMENTED** [review]
Thoughts on moving this to a `Getting Started with Monitoring` guide? That way folks following any getting started guide can then move on to monitoring.

**Comment by chrisnegus** [comment]
> Thoughts on moving this to a `Getting Started with Monitoring` guide? That way folks following any getting started guide can then move on to monitoring.

One way I've done this sort of thing in the past was to have as sentence at the end of the getting started guide like: "With the basic setup of Karpenter complete, here are ways of extending your configuration." The have a bullet list of links to optional features they can add. Then this and other content could go in tasks or with other getting started guides.

**Comment by felix-zhe-huang** [comment]
Do we plan to provide a default dashboard as part of the guide? I can help move the dashboard definition into the helm chart override to simplify the deployment steps.

**Comment by ellistarn** [comment]
> Do we plan to provide a default dashboard as part of the guide? I can help move the dashboard definition into the helm chart override to simplify the deployment steps.

This would be a great followup!

**Pull request closed without merging**
