### PR TITLE
feat: added annotations and debug level to the helm chart

### PR DESCRIPTION
**Pull request by alekc**
**1. Issue, if available:**
Closes https://github.com/aws/karpenter/issues/1263

**2. Description of changes:**
Added annotations to the controller and webhook, added support for variation of global logging level from helm

**3. How was this change tested?**
Generated helm templates

**4. Does this change impact docs?**
- [x] Yes, PR includes docs updates
- [ ] Yes, issue opened: *link to issue*
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by stevehipwell** [comment]
@alekc the Helm chart refactor PR (https://github.com/aws/karpenter/pull/1145) has added annotations using the idiomatic `podAnnotations` key (it's also added `podLabels`), hopefully this chart refactor will be released soon. If you need annotations added before then it might be best to use the the `podAnnotations` key? I haven't added `additionalAnnotations` to match the `additionalLabels` value but I could?

**Comment by alekc** [comment]
@stevehipwell missed your PR. I am ok with closing this one and waiting for yours, but we should still add a specific annotations for both controllers and webhooks (not on the pod level, but the root). Several operators relies on those (i.e. https://github.com/stakater/Reloader) and I don't think there is a reason not to give this flexibility.

**Comment by stevehipwell** [comment]
@alekc the pods have been merged but I'll add the top level `additionalAnnotations` and log level.

**Comment by alekc** [comment]
cool. Closing this one then

**Pull request closed without merging**
