### PR TITLE
Pricing Endpoint for eu-central-1

### LINKED ISSUE #4475: Add Pricing Endpoint for eu-central-1
### Description

**What problem are you trying to solve?**

There is currently a pricing endpoint in us-east-1 and ap-south-1. Recently, a pricing endpoint was released in eu-central-1. Karpenter should be updated to use the new pricing endpoint if in an eu-* region. 

https://github.com/aws/karpenter/blob/main/pkg/providers/pricing/pricing.go#L89

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by riteshsonawane1372**
Fixes #4475 

**Description**
Allow pricing endpoint for eu* to be eu-central-1

**How was this change tested?**

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [x] Yes, issue opened: #4475 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by njtran** [comment]
Thanks for the PR. Can you run `make presubmit` to make sure that things are working from this change and the linter runs? 

Can you also share how you tested this?

**Comment by riteshsonawane1372** [comment]
> Thanks for the PR. Can you run `make presubmit` to make sure that things are working from this change and the linter runs?
> 
> Can you also share how you tested this? @riteshsonawane1372

@njtran `make presubmit` ran successfully, previously had some issue with the local setup. 

Screenshot from 2023-08-30 08-49-23

**Comment by riteshsonawane1372** [comment]
Screenshot from 2023-08-30 09-27-45

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀

**Comment by jonathan-innis** [comment]
Validated in an `eu` region

**Comment by tbugfinder** [comment]
https://github.com/aws/karpenter/issues/2604

**Pull request merged**
