### PR TITLE
Added hugo to go toolchain

### PR DESCRIPTION
**Pull request by ellistarn**
**1. Issue, if available:**

**2. Description of changes:**
Dependency in a language other than go? 🙅 

**3. How was this change tested?**

**4. Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: *link to issue*
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by njtran** [comment]
AFAIK, Hugo is only used for creating releases. While small, I'm don't think we should add in tools that aren't necessary for the everyone into the toolchain, since it adds another method of tool installation failure. WDYT?

**Comment by geoffcline** [comment]
I think this is the incorrect version of Hugo. we need Hugo-extended for the docsy theme. 

I am unfamiliar with how go installs Hugo, so maybe it defaults to extended?

appreciate the gitingore updates

**Comment by ellistarn** [comment]
> I think this is the incorrect version of Hugo. we need Hugo-extended for the docsy theme.
> 
> I am unfamiliar with how go installs Hugo, so maybe it defaults to extended?
> 
> appreciate the gitingore updates

I found it was nice to use the same packaging mechanism for all our dependencies. e.g. `brew` only works on macs, and not always for the new M1s. I'm using the latest version here: https://github.com/gohugoio/hugo

**Comment by geoffcline** [comment]
excellent!

**Review by geoffcline — APPROVED** [review]

**Pull request merged**
