### PR TITLE
fix: Convert `karpenter.sh/managed-by` label to annotation

### LINKED ISSUE #4004: incompatible charset for the label `karpenter.sh/managed-by`
### Version

__Karpenter Version:__ v0.28.0-rc.2
__Kubernetes Version:__ v1.23.17

### Expected Behavior

We use this pattern for the name of our self managed k8s clusters on AWS `aws:ACCOUNT_ID:AWS_REGION:CLUSTER_NAME` because we are running ~ 200 clusters with some accounts hosting more than one cluster. 

migrating to karpenter initially resulted in the issue #3697,  where the CLUSTER_NAME was invalid to be used as a name for AWS LaunchTemplate

now the same issue re-appeared but with the `karpenter.sh/managed-by` label
[kubernetes label values has different charset](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set)

the expected behavior is to be able to upgrade karpenter version to `v0.28.0-rc.2` with the same CLUSTER_NAME

### Actual Behavior

after creating the EC2 instance, `CloudProvider.instanceToMachine` fails to create a `v1alpha5.Machine` because the value of the instance tag `v1alpha5.ManagedByLabelKey` is invalid as a Kubernetes label value.

### Steps to Reproduce the Problem

create a cluster with the provided pattern as cluster_name

### Resource Specs and Logs

```json
 {
    "severity": "ERROR",
    "timestamp": "2023-06-06T12:16:51.324108805Z",
    "logger": "controller",
    "caller": "controller/controller.go:273",
    "message": "Reconciler error",
    "commit": "b0ac6ed-dirty",
    "controller": "machine_lifecycle",
    "controllerGroup": "karpenter.sh",
    "controllerKind": "Machine",
    "Machine": {
      "name": "karpenter-default-cqt8w"
    },
    "namespace": "",
    "name": "karpenter-default-cqt8w",
    "reconcileID": "020f1f90-0823-4368-89b1-1eceff8284de",
    "error": "Machine.karpenter.sh \"karpenter-default-cqt8w\" is invalid: metadata.labels: Invalid value: \"aws:ACCOUNT_ID:AWS_REGION:CLUSTER_NAME\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')",
    "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234"
  }
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by jonathan-innis**
Fixes #4004 

**Description**

Converts the `karpenter.sh/managed-by` from a label to an annotation. This creates consistency between the Machine that is returned from the CloudProvider on a Get() and the resolved Machine from a Create(). This also fixes the issue with character restrictions and length restrictions on labels that don't exist on annotations.

**How was this change tested?**

* Manual Validation
* `/karpenter snapshot`

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [x] No

**Release Note**

```release-note
None
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by bwagner5 — COMMENTED** [review]
lgtm - looks like the upgrade test keeps failing

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Review by jonathan-innis — COMMENTED** [review]
/karpenter snapshot

**Comment by jonathan-innis** [comment]
> looks like the upgrade test keeps failing

It was failing due to a separate issue. Trying the snapshot run again.

**Review by bwagner5 — APPROVED** [review]
lgtm

**Pull request merged**
