### PR TITLE
Fixes broken document links

### PR DESCRIPTION
**Pull request by zeagord**
**1. Issue, if available:**
Yes, https://github.com/aws/karpenter/issues/1198

**2. Description of changes:**
Fixes broken document links

**3. How was this change tested?**

**4. Does this change impact docs?**
- [X] Yes, PR includes docs updates
- [X] Yes, issue opened: [*link to issue*](https://github.com/aws/karpenter/issues/1198)
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ellistarn** [comment]
Hey @zeagord , I was just talking to @geoffcline about this issue. The challenge is that the grafana-values.yaml file needs to be versioned with `{{latest_release_version}}`, but since it's a static file, it will need to be updated for each version. We were thinking that we could move the values.yaml into the doc itself, so that we can inject this version (`preview` in this case) into the docs.

**Comment by bwagner5** [comment]
Just to throw out another option on versioning this: We could also treat this yaml as a release asset and upload to github release assets w/ our github action release process. We will need to do something like this eventually to sync this to grafana.com to be installed like this https://grafana.com/grafana/dashboards/650

**Comment by zeagord** [comment]
Both of your points are valid. I will fix the link and point to the preview like `https://karpenter.sh/preview/getting-started/karpenter-pod-metrics.json`. 

In another PR, we can automate publishing the Grafana dashboards to the `grafana.com` via GH Actions. 

Does that work?

**Comment by ellistarn** [comment]
Specifically this will need to be versioned
```
dashboards:
  default:
    pod-dashboard:
      url: https://karpenter.sh/preview/getting-started/karpenter-pod-metrics.json
    node-dashboard:
      url: https://karpenter.sh/preview/getting-started/karpenter-node-metrics.json
```

**Comment by zeagord** [comment]
Closing this as it is fixed in the release https://github.com/aws/karpenter/releases/tag/v0.5.6

**Pull request closed without merging**
