### PR TITLE
test: Fix Scale testing timeouts on consolidation 

### PR DESCRIPTION
**Pull request by engedaam**
Fixes #N/A 

**Description**
- fixes scale testing failures  
- Enable consolidation for consolidation tests 
- Fix expiration test 

**How was this change tested?**
- `/karpenter scale`

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by engedaam — COMMENTED** [review]
/karpenter scale

**Review by engedaam — COMMENTED** [review]
/karpenter scale

**Review by engedaam — COMMENTED** [review]
/karpenter scale

**Review by engedaam — COMMENTED** [review]
/karpenter scale

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀

**Pull request merged**
