### PR TITLE
rework search indexing

### PR DESCRIPTION
**Pull request by tzneal**
**1. Issue, if available:**
N/A

**2. Description of changes:**

- make all content non-indexable by default
- during release, ensure everything is non-indexeable and
  only enable indexing for the current release

**3. How was this change tested?**

Went to Netlify preview and searched, only v0.8.2 results displayed.

**4. Does this change impact docs?**
- [x] Yes, PR includes docs updates
- [ ] Yes, issue opened: *link to issue*
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by spring1843** [comment]
@tzneal can you explain what drives this change? What are we trying to accomplish?

I am concerned with our search engine rankings, if we constantly change the index-ability of our pages there's a chance it lowers our ranking. Maybe we should keep the "preview" always indexible.

**Comment by tzneal** [comment]
> @tzneal can you explain what drives this change? What are we trying to accomplish?
> 

The search on karpenter.sh isn't useful as it pulls results from every release we've ever had.  It will only continue to get  worse.
Screen Shot 2022-04-13 at 12 08 27 PM

> I am concerned with our search engine rankings, if we constantly change the index-ability of our pages there's a chance it lowers our ranking. Maybe we should keep the "preview" always indexible.

I didn't realize this also caused meta tags to be added to the HTML output:

```<meta name=ROBOTS content="NOINDEX, NOFOLLOW">```

**Comment by spring1843** [comment]
Thank you for explaining that @tabern.

For this approach to work we need to be able to edit older files. Since we are planning to move the older files away from the repo at some point, doing so will become difficult if not impossible. Is it conceivable to have the same outcome without having to edit the old versions?

**Comment by tzneal** [comment]
> Thank you for explaining that @tzneal
> 
> For this approach to work we need to be able to edit older files. Since we are planning to move the older files away from the repo at some point, doing so will become difficult if not impossible. Is it conceivable to have the same outcome without having to edit the old versions?

This just modifies the markdown input files that are then rendered into HTML.  Presumably we will never lose the ability to modify those files. That there is a directory called "v0.8.2" is that happens to contain our doc snapshots at a point in time is just an artifact of how the directory structure is laid out.  Hugo renders those files each time it generates the site.

**Comment by bwagner5** [comment]
We may want to wait on PR https://github.com/aws/karpenter/pull/1674 since this will only work for the latest version. I'm not sure how far along #1674 is

**Comment by tzneal** [comment]
> We may want to wait on PR #1674 since this will only work for the latest version. I'm not sure how far along #1674 is

I viewed that as a feature, I'm good either way.

**Pull request closed without merging**
