### PR TITLE
Parameters needs to be passed like settings.aws.

### PR DESCRIPTION
**Pull request by bhushanchirmade**
Fixes # 

**Description**

**How was this change tested?**

*

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [ ] No

**Release Note**

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bwagner5** [comment]
Can you copy those to the preview docs as well?

**Comment by bhushanchirmade** [comment]
> 

Where? I am not sure where it is located.

**Comment by bwagner5** [comment]
> > 
> 
> Where? I am not sure where it is located.

https://github.com/aws/karpenter/blob/main/website/content/en/preview/getting-started/getting-started-with-eksctl/scripts/step08-apply-helm-chart.sh

**Comment by bhushanchirmade** [comment]
> > > 
> > 
> > 
> > Where? I am not sure where it is located.
> 
> https://github.com/aws/karpenter/blob/main/website/content/en/preview/getting-started/getting-started-with-eksctl/scripts/step08-apply-helm-chart.sh

Done.

**Review by bwagner5 — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
