### PR TITLE
feat: make karpenter-global-settings ConfigMap management optional

### PR DESCRIPTION
**Pull request by morremeyer**
Relates to #2893

**Description**

This enables management of the ConfigMap outside of this chart, which is needed when e.g. managing the EKS cluster with terraform to be able to set the cluster name without manually syncing configuration files.

**How was this change tested?**

- Ran `helm template` locally to verify
- Added workflow using the **chart-testing** tool to lint the charts

**Does this change impact docs?**
- [x] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jmdeal** [comment]
Thanks for the contribution, however the next release is going to include a complete migration to environment variables / cli args for configuration. The linked issue should have probably been closed by #4789.

**Comment by jmdeal** [comment]
Didn't mean to close, it sounded like in the issue the changes made in #4789 would solve your issue. Is that correct or are there other changes that would need to be made?

**Comment by morremeyer** [comment]
@jmdeal That's excellent news, I didn't catch #4789!

#2893 should probably also be closed and linked to #4789.

Is there a timeline for the release?

**Comment by jmdeal** [comment]
We don't generally disclose release timelines but it should be soon.

**Pull request closed without merging**
