### PR TITLE
fix: China Pricing Endpoint

### LINKED ISSUE #4658: Add China pricing endpoint
### Description

**Observed Behavior**:

We are trying to run Karpenter 0.29.2 in a Kubernetes cluster running in AWS China. 

Upon startup, Karpenter pods fail with the following logs and start CrashLooping:

```
2023-08-30T13:38:35.458Z DEBUG Successfully created the logger.
2023-08-30T13:38:35.458Z DEBUG Logging level set to: debug
2023-08-30T13:38:38.079Z DEBUG controller retrieving region from IMDS {"commit": "34d50bf-dirty"}
2023-08-30T13:38:46.282Z FATAL controller Checking EC2 API connectivity, WebIdentityErr: failed to retrieve credentials caused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://s3.cn-north-1.amazonaws.com.cn/ACCOUNT_ID-CLUSTER_ID-oidc-pod-identity-v2
status code: 400, request id: xxxxxxxx-yyyy-zzzz-aaaa-asdasdasd {"commit": "34d50bf-dirty"}
```

however, the OIDC provider is there:

dsa

The AWS role is configured correctly (works in AWS Global), ARN's are in the right partition (`aws-cn` instead of `aws`), ... . The pod is getting the right credentials injected by the IRSA webhook.

```
AWS_STS_REGIONAL_ENDPOINTS:   regional
AWS_ROLE_ARN: arn:aws-cn:iam::ACCOUNT_ID:role/CLUSTER_ID-Karpenter-Role
AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

**Expected Behavior**:

Karpenter should be able to find the OIDC provider in the AWS account since the provider is there and Karpenter's role allows accessing it.

**Reproduction Steps** (Please include YAML):

1. Create an OIDC provider and an IAM Role for Karpenter according to the official documentation
1. Install Karpenter in a vanilla Kubernetes cluster running in AWS China
1. Configure Karpenter to use the Role created in point 1

**Versions**:
- Chart Version: 0.29.2
- Kubernetes Version (`kubectl version`):  1.24.13

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

cc @paurosello

### PR DESCRIPTION
**Pull request by paurosello**
Fixes #4658

**Description**

Pricing endpoint for China was wrong as the generated auth tokens are not valid in the Asia Pacific region. Also it's best to get prices from the same region.

**How was this change tested?**

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by paurosello** [comment]
Do not merge yet, testing changes

**Comment by paurosello** [comment]
Apparently China has no pricing endpoint... but it somehow works from the CLI
```
caused by: Post "https://api.pricing.cn-north-1.amazonaws.com.cn/": dial tcp: lookup api.pricing.cn-north-1.amazonaws.com.cn on 10.1.1.2:53: no such host; RequestError: send request failed
```

```
bash-4.2$ aws ec2   describe-spot-price-history --region=cn-north-1
{
    "SpotPriceHistory": [
        {
            "AvailabilityZone": "cn-north-1b",
            "InstanceType": "c3.4xlarge",
            "ProductDescription": "Red Hat Enterprise Linux",
            "SpotPrice": "3.210700",
            "Timestamp": "2023-09-22T09:06:30+00:00"
        },
```

**Comment by paurosello** [comment]
I see that command is using the EC2 api, no the pricing one

**Comment by paurosello** [comment]
According to this announcement https://www.amazonaws.cn/en/new/2018/programmatic-access-to-pricing-information-in-china-via-aws-price-list-api/ it should be available but can't find any information about it

**Comment by paurosello** [comment]
Good news, cn-northwest-1 has the pricing endpoint 
 
`2023-09-22T10:33:43.055Z    DEBUG    controller.pricing    updated on-demand pricing    {"commit": "7751588-dirty", "instance-type-count": 263}`

**Comment by njtran** [comment]
Thanks for the PR @paurosello, I need to look into how available this endpoint is before we accept this. Will get back to you on this 👍

**Review by tzneal — APPROVED** [review]
The China partition pricing endpoint is now GA. https://docs.amazonaws.cn/en_us/aws-cost-management/latest/APIReference/Welcome.html#Welcome_AWS_Price_List_Service

**Pull request merged**
