### PR TITLE
fix: cherry-pick: Fix externeal cloudprovider taint add in 1.26 (#375)

### PR DESCRIPTION
**Pull request by ellistarn**
Fixes #N/A 

**Description**

See: https://github.com/aws/karpenter-core/pull/375

**How was this change tested?**

https://github.com/aws/karpenter/actions/runs/5340415940

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [X] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ellistarn — COMMENTED** [review]
/karpenter snapshot

**Review by ellistarn — COMMENTED** [review]
/karpenter snapshot

**Review by ellistarn — COMMENTED** [review]
/karpenter snapshot

**Comment by jonathan-innis** [comment]
Tested manually. Ran a deployment with hostname anti-affinity for 200 replicas which should spawn up 200 machines and 200 nodes. Karpenter spawned up 200 machines followed by 200 nodes and did not exceed past this number when the external cloudprovider taint was added to the node on startup.

**Comment by jonathan-innis** [comment]
Plan to fast-follow this release with a bump to our E2E test suite to 1.26 and additional conformance testing to run the e2e test suite prior to release of all supported Kubernetes versions for Karpenter.

**Pull request merged**
