### PR TITLE
docs: Terraform Getting Started - Authorize to ECR

### LINKED ISSUE #2849: Unable to install helm with oci URL via terraform
### Is an existing page relevant?

https://karpenter.sh/v0.18.1/getting-started/getting-started-with-terraform/

### What karpenter features are relevant?

Trying to install via `terraform` fails with this message:

```
│ Error: could not download chart: failed to download "oci://public.ecr.aws/karpenter/karpenter" at version "v0.18.1"
```

### How should the docs be improved?

It is necessary to instruct `helm_release` provider to obtain token for authentication with oci repository
```tf
data "aws_ecrpublic_authorization_token" "token" {}
resource "helm_release" "karpenter" {

  repository_username = data.aws_ecrpublic_authorization_token.token.user_name
  repository_password = data.aws_ecrpublic_authorization_token.token.password
  lifecycle {
    ignore_changes = [ repository_password ]
  }

  namespace        = "karpenter"
  create_namespace = true

  name       = "karpenter"
  repository = "oci://public.ecr.aws/karpenter"
  chart      = "karpenter"
  version    = "v0.18.1"
...
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by slobo**
Fixes #2849

**Description**

**How was this change tested?**

* Locally - we use this code to deploy karpenter to our EKS cluster

**Does this change impact docs?**
- [x] Yes, PR includes docs updates

**Release Note**

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by FernandoMiguel** [comment]
i tried this on a test cluster and it forced a new helm deployment on each apply, and also a drift on the token.
so far we never needed auth for the public ECR gallery. 
this seems unnecessary

**Comment by slobo** [comment]
Did you include the `lifecycle` bits as well, that should prevent it trying to apply every time. Perhaps also need to add `repository_username` to `ignore_changes`?

**Comment by FernandoMiguel** [comment]
with the lifecycle it eventually expired and stopped working

**Comment by slobo** [comment]
OK, I see that happening to me too now, I guess I never let it sit for long enough. 

I wonder what's different in my environment that prevents helm from accessing `public.ecr.aws` without the token. Are you deploying from within AWS?

**Comment by FernandoMiguel** [comment]
@slobo both from atlantis (ec2) and my mbp via aws SSO

**Comment by bwagner5** [comment]
Generally with ECR public, you either need a token or you need to have no token in your docker config (or whatever you're using to do the push / pulls) to use anonymous ECR auth. If you have auth setup that is expired, anonymous auth won't happen.  

It sounds like this PR is unnecessary then if you are able to use anonymous auth with ecr public?

**Comment by slobo** [comment]
Thanks for your input folks. I was able to get this to work without `aws_ecrpublic_authorization_token` by removing an old authorization token from `~/.config/helm/registry/config.json`. 

Do you know of a way to force terraform `helm_release` resource to disregard anything stored in users home directory and force the use of anonymous authentication? I had tried setting the `repository_{username,password}` to empty strings (`""`), but that didn't work...

**Comment by slobo** [comment]
It seems that there is an upcoming fix to terraform that will enable us to use the public token without forcing re-deployment: https://github.com/hashicorp/terraform-provider-helm/pull/862

**Comment by tzneal** [comment]
Looks like a `docker logout public.ecr.aws` solves this. I'll close for now, but feel free to re-open if you disagree.

**Pull request closed without merging**
